
# html lang
language: zh-cn

# main menu navigation
menu:
  Home: 
    url: /
    icon: fas fa-home
  About:
    url: /about
    icon: fas fa-user-astronaut
  Archives: 
    url: /archives
    icon: fas fa-tags
  Categories: 
    url: /categories
    icon: fas fa-archive
  Tags: 
    url: /tags
    icon: fas fa-tags
  Search: 
    url: /search
    icon: fas fa-search
# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/airy.css
- /lib/instantsearch/instantsearch.css
- /lib/font-awesome/css/all.min.css
- /lib/prism/prism.css
- /lib/fancybox/fancybox.min.css
- /lib/iconfont/iconfont.css

custom_logo:
  enabled: false
  image: /images/voidsky.png

# js used in all file
scripts:
- /js/airy.js

# js used in post
postjs:
# - /js/scrollspy.js
# - /lib/fancybox/fancybox.min.js

searchjs:
# - /js/search.js

# search bar
algolia:
  applicationID: UVD02QN2NI
  adminApiKey: 7bc546079341b1fa8311cc8931427dc4
  apiKey: 94932d8504e5be4abfff9c994dd2880e
  indexName: hksite
  
categories:
  english:
    img: /images/avatar.jpg
    intro: '我的英语之路'
    
leancloud: false

toc: true

profile:
  photo:
    url: https://ws2.sinaimg.cn/large/006tNc79gy1fvu2ao3m3vj30uq0tgne4.jpg
    round: true 
  introduce: '有时候折腾一下，只为了证明自己的重要性'

social:
  github:
    icon: fab fa-github
    enable: true
    url: http://github.com/hk029
  # 微信的url填二维码的图片地址
  weixin:
    qrcode: true
    icon: fab fa-weixin
    enable: true
    url: /images/weixin.jpg
  weibo:
    icon: fab fa-weibo
    enable: true
    url: /
  juejin:
    icon: iconfont icon-juejin
    enable: true
    url:
  csdn:
    icon: iconfont icon-logo_csdn
    enable: true
    url: https://blog.csdn.net/hk2291976
  jianshu:
    icon: iconfont icon-jianshu 
    enable: true
    url: https://www.jianshu.com/u/30f737ee0051
