
# html lang
language: zh-cn

# main menu navigation
menu:
  Home: 
    url: /
    icon: fas fa-home
  About:
    url: /about
    icon: fas fa-user-astronaut
  Archives: 
    url: /archives
    icon: fas fa-tags
  Categories: 
    url: /categories
    icon: fas fa-th
  Tags: 
    url: /tags
    icon: fas fa-tags
# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/airy.css
- /lib/font-awesome/css/all.min.css
- /lib/fancybox/fancybox.min.css
- /lib/iconfont/iconfont.css
- https://fonts.googleapis.com/css?family=Abril+Fatface|Almendra:700|Berkshire+Swash|Bungee+Hairline|Cinzel:900|Limelight|Orbitron:900|Paytone+One|Playfair+Display+SC:900|Trochut:700
# - /lib/highlight/styles/atom-one-dark.css
# scripts loaded in the end of the body

custom_logo:
  enabled: false
  image: /images/voidsky.png

# js used in all file
scripts:
- /lib/highlight/highlight.pack.js
- /lib/jquery/jquery.min.js
- /lib/fancybox/fancybox.min.js
- /js/airy.js

# js used in post
postjs:
- /js/scrollspy.js


categories:
  english:
    img: /images/avatar.jpg
    intro: '我的英语之路'
    
leancloud: false
toc: true

profile:
  photo:
    url: https://ws2.sinaimg.cn/large/006tNc79gy1fvu2ao3m3vj30uq0tgne4.jpg
    round: true 
  introduce: '我是要成为海贼王的男人'

social:
  github:
    icon: fab fa-github
    enable: true
    url: http://github.com/hk029
  # 微信的url填二维码的图片地址
  weixin:
    qrcode: true
    icon: fab fa-weixin
    enable: true
    url: /images/weixin.jpg
  weibo:
    icon: fab fa-weibo
    enable: true
    url: /
  juejin:
    icon: iconfont icon-juejin
    enable: true
    url:
  csdn:
    icon: iconfont icon-logo_csdn
    enable: true
    url:
  jianshu:
    icon: iconfont icon-jianshu 
    enable: true
    url:
